# This is a basic workflow to help you get started with Actions

name: Github CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "0-develop" branch
  push:
    branches: [ "0-develop" ]
  pull_request:
    branches: [ "0-develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: RunIde with Gradle
        uses: ./gradlew runIde

