name: Build ShelveMe

on:
  push:
    branches:
      - 0-develop
  pull_request:
    branches:
      - 0-develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [ 17,18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}

      - name: Build with Gradle
        run: ./gradlew build
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: Run tests
        run: ./gradlew test

      - name: Verify Plugin
        run: ./gradlew verifyPlugin
