name: ShelveMeBuild
on:
  pull_request:
    branches:
      - 0-develop
  push:
    branches:
      - 0-develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: RunIde with Gradle
        uses: ./gradlew runIde

